import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body className={inter.className}>
          <header>
            <Link href="/"
                  className="text-3xl font-bold">
                  Home
            </Link>
            <Link href="/about"
                  className="text-3xl font-bold">
                  About
            </Link>
            <Link href="/events"
                  className="text-3xl font-bold">
                  Events
            </Link>
            <Link href="/team"
                  className="text-3xl font-bold">
                  Team
            </Link>
          </header>
          <main>
            {children}
          </main>
        </body>
      </html>
  );
}
